"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 15:32:15.124009
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "soldiers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("personal_number_hash", sa.String(length=64), nullable=False),
        sa.Column("personal_number_enc", sa.LargeBinary(), nullable=False),
        sa.Column("full_name_enc", sa.LargeBinary(), nullable=False),
        sa.Column("unit_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soldiers")),
        sa.UniqueConstraint(
            "personal_number_hash", name=op.f("uq_soldiers_personal_number_hash")
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("totp_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("totp_last_step", sa.BigInteger(), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('uploader', 'reviewer', 'admin', 'auditor')",
            name=op.f("ck_users_role"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("object_type", sa.String(length=40), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False
    )
    op.create_table(
        "consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("soldier_id", sa.Uuid(), nullable=False),
        sa.Column("document_ref", sa.String(length=120), nullable=False),
        sa.Column("signed_on", sa.Date(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired')",
            name=op.f("ck_consents_status"),
        ),
        sa.CheckConstraint(
            "valid_until >= valid_from", name=op.f("ck_consents_validity_order")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
            name=op.f("fk_consents_recorded_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["soldier_id"],
            ["soldiers.id"],
            name=op.f("fk_consents_soldier_id_soldiers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_index(
        op.f("ix_consents_soldier_id"), "consents", ["soldier_id"], unique=False
    )
    op.create_index(op.f("ix_consents_status"), "consents", ["status"], unique=False)
    op.create_table(
        "imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("rows_total", sa.Integer(), nullable=False),
        sa.Column("rows_accepted", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column(
            "reject_reasons",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'done', 'failed')", name=op.f("ck_imports_status")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_imports_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
    )
    op.create_index(op.f("ix_imports_sha256"), "imports", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_imports_uploaded_by"), "imports", ["uploaded_by"], unique=False
    )
    op.create_table(
        "watchlist_terms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("term_hash", sa.String(length=64), nullable=False),
        sa.Column("term_enc", sa.LargeBinary(), nullable=False),
        sa.Column("aliases_enc", sa.LargeBinary(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('codename', 'site', 'unit', 'other')",
            name=op.f("ck_watchlist_terms_kind"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high')",
            name=op.f("ck_watchlist_terms_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_watchlist_terms_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_terms")),
        sa.UniqueConstraint("term_hash", name=op.f("uq_watchlist_terms_term_hash")),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("soldier_id", sa.Uuid(), nullable=False),
        sa.Column("consent_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=10), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("status_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_import_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('instagram', 'tiktok', 'facebook')",
            name=op.f("ck_accounts_platform"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'closed', 'unknown', 'not_found')",
            name=op.f("ck_accounts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["consents.id"],
            name=op.f("fk_accounts_consent_id_consents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["soldier_id"],
            ["soldiers.id"],
            name=op.f("fk_accounts_soldier_id_soldiers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_import_id"],
            ["imports.id"],
            name=op.f("fk_accounts_source_import_id_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("platform", "username", name="platform_username"),
    )
    op.create_index(
        op.f("ix_accounts_consent_id"), "accounts", ["consent_id"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_soldier_id"), "accounts", ["soldier_id"], unique=False
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "media",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "delete_after > collected_at",
            name=op.f("ck_posts_retention_after_collection"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_posts_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint("account_id", "content_hash", name="account_content"),
    )
    op.create_index(op.f("ix_posts_account_id"), "posts", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_posts_delete_after"), "posts", ["delete_after"], unique=False
    )
    op.create_index(op.f("ix_posts_posted_at"), "posts", ["posted_at"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("reason_enc", sa.LargeBinary(), nullable=False),
        sa.Column("evidence_enc", sa.LargeBinary(), nullable=True),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('uniform', 'equipment', 'classified_document', 'screen_photo', 'codename', 'location', 'text_pattern')",
            name=op.f("ck_findings_kind"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high')", name=op.f("ck_findings_severity")
        ),
        sa.CheckConstraint(
            "status IN ('new', 'in_review', 'confirmed', 'dismissed', 'escalated')",
            name=op.f("ck_findings_status"),
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 1", name=op.f("ck_findings_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_findings_post_id_posts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint(
            "post_id", "kind", "evidence_hash", name="post_kind_evidence"
        ),
    )
    op.create_index(op.f("ix_findings_post_id"), "findings", ["post_id"], unique=False)
    op.create_index(
        op.f("ix_findings_severity"), "findings", ["severity"], unique=False
    )
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("note_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('confirmed', 'dismissed', 'escalated')",
            name=op.f("ck_reviews_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_reviews_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_reviews_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index(
        op.f("ix_reviews_finding_id"), "reviews", ["finding_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_reviewer_id"), "reviews", ["reviewer_id"], unique=False
    )
    # ### end Alembic commands ###

    # Append-only audit trail: any UPDATE or DELETE is rejected by the database itself,
    # so even a compromised application account cannot rewrite history.
    # (PostgreSQL only; the SQLite used by unit tests has no equivalent trigger here.)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE FUNCTION audit_log_append_only() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_log is append-only';
            END;
            $$ LANGUAGE plpgsql
            """)
        op.execute("""
            CREATE TRIGGER audit_log_no_update_delete
            BEFORE UPDATE OR DELETE ON audit_log
            FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()
            """)


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_reviewer_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_finding_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_post_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_posts_posted_at"), table_name="posts")
    op.drop_index(op.f("ix_posts_delete_after"), table_name="posts")
    op.drop_index(op.f("ix_posts_account_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_accounts_soldier_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_consent_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("watchlist_terms")
    op.drop_index(op.f("ix_imports_uploaded_by"), table_name="imports")
    op.drop_index(op.f("ix_imports_sha256"), table_name="imports")
    op.drop_table("imports")
    op.drop_index(op.f("ix_consents_status"), table_name="consents")
    op.drop_index(op.f("ix_consents_soldier_id"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("soldiers")
    # ### end Alembic commands ###
