"""post analyzed version

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 16:08:38.957971
"""

from alembic import op
import sqlalchemy as sa

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("analyzed_version", sa.String(length=40), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "analyzed_version")
    # ### end Alembic commands ###
