"""review reason

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 19:01:32.938427
"""

from alembic import op
import sqlalchemy as sa

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("reason", sa.String(length=20), nullable=True))
    op.create_check_constraint(
        op.f("ck_reviews_reason"),
        "reviews",
        "reason IS NULL OR reason IN ('not_relevant', 'common_word', 'public_info', 'other')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_reviews_reason"), "reviews", type_="check")
    op.drop_column("reviews", "reason")
    # ### end Alembic commands ###
