"""learning

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 20:13:24.249196
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "golden_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("text_enc", sa.LargeBinary(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('uniform', 'equipment', 'classified_document', 'screen_photo', 'codename', 'location', 'text_pattern')",
            name=op.f("ck_golden_cases_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_golden_cases_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_golden_cases")),
    )
    op.create_table(
        "learning_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("params_enc", sa.LargeBinary(), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("trained_on", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("trained_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('candidate', 'shadow', 'active', 'retired', 'rejected')",
            name=op.f("ck_learning_models_status"),
        ),
        sa.ForeignKeyConstraint(
            ["trained_by"],
            ["users.id"],
            name=op.f("fk_learning_models_trained_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_models")),
        sa.UniqueConstraint("version", name=op.f("uq_learning_models_version")),
    )
    op.create_index(
        op.f("ix_learning_models_status"), "learning_models", ["status"], unique=False
    )
    op.create_table(
        "model_approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["learning_models.id"],
            name=op.f("fk_model_approvals_model_id_learning_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_model_approvals_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_approvals")),
        sa.UniqueConstraint("model_id", "user_id", name="model_user"),
    )
    op.create_index(
        op.f("ix_model_approvals_model_id"),
        "model_approvals",
        ["model_id"],
        unique=False,
    )
    op.add_column(
        "findings",
        sa.Column("adjusted_score", sa.Numeric(precision=4, scale=3), nullable=True),
    )
    op.add_column("findings", sa.Column("scored_by_model", sa.Uuid(), nullable=True))
    op.add_column(
        "findings",
        sa.Column("shadow_score", sa.Numeric(precision=4, scale=3), nullable=True),
    )
    op.add_column("findings", sa.Column("shadow_model", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_findings_shadow_model_learning_models"),
        "findings",
        "learning_models",
        ["shadow_model"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_findings_scored_by_model_learning_models"),
        "findings",
        "learning_models",
        ["scored_by_model"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_findings_scored_by_model_learning_models"),
        "findings",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_findings_shadow_model_learning_models"), "findings", type_="foreignkey"
    )
    op.drop_column("findings", "shadow_model")
    op.drop_column("findings", "shadow_score")
    op.drop_column("findings", "scored_by_model")
    op.drop_column("findings", "adjusted_score")
    op.drop_index(op.f("ix_model_approvals_model_id"), table_name="model_approvals")
    op.drop_table("model_approvals")
    op.drop_index(op.f("ix_learning_models_status"), table_name="learning_models")
    op.drop_table("learning_models")
    op.drop_table("golden_cases")
    # ### end Alembic commands ###
